export const colors: string[] = [
    'Red',
    'Blue',
    'Green',
    'Yellow',
    'Orange',
    'Purple',
    'Pink',
    'Brown',
    'Gray',
    'Black',
    'White',
    'Cyan',
    'Magenta',
    'Indigo',
    'Turquoise',
    'Coral',
    'Teal',
    'Lime',
    'Maroon',
    'Navy',
    'Olive',
    'Gold',
    'Silver',
    'Salmon',
    'Plum',
    'Lavender',
    'Sky Blue',
    'Rose',
    'Beige',
    'Mint Green',
    'Peach',
    'Steel Blue',
    'Forest Green',
    'Orchid',
    'Slate Gray',
    'Periwinkle',
    'Khaki',
    'Tomato',
    'Royal Blue',
    'Sandy Brown',
    'Slate Blue',
    'Sienna',
    'Crimson',
    'Dark Green',
    'Cornflower Blue',
    'Ivory',
    'Dark Gray',
    'Pale Pink',
    'Dark Orchid',
    'Light Coral'
];

export const sizes: string[] = [
    'XS',
    'S',
    'M',
    'L',
    'XL',
    'XXL'    
];